const path = require("path");

const ASSETS_DIR = path.join(__dirname, "..", "assets");
const TEAMS_LOGOS_DIR = path.join(__dirname, "..", "..", "teams_logos");

module.exports = {
  ASSETS_DIR,
  TEAMS_LOGOS_DIR,
  CANVAS_WIDTH: 1080,
  CANVAS_HEIGHT: 1350,
  RANKING_HEIGHT: 1350,
  MATCH_RESULTS_HEIGHT: 1350,
  STATISTICS_HEIGHT: 1350,

  TITLE_COLOR: "#f1d11c",
  LEAGUE_LABEL_COLOR: "rgba(255,255,255,0.64)",
  SCORE_RECT_COLOR: "rgba(0,0,0,0.74)",
  STATS_CARD_COLOR: "rgba(255,255,255,0.4)",
  STATS_CARD_RADIUS: 16,
  STATS_CARD_HORIZONTAL_INSET: 200,
  STATS_TITLE_FONT_SIZE: 32,
  STATS_VS_FONT_SIZE: 28,
  STATS_VALUE_FONT_SIZE: 110,
  TEXT_WHITE: "#FFFFFF",
  TEXT_RED: "#e63946",

  FONT_FAMILY: "Poppins",
  TITLE_FONT_SIZE: 69,
  RESULTS_FONT_SIZE: 40,
  LEAGUE_FONT_SIZE: 24,
  APLAZADO_FONT_SIZE: 32,
  LEADERBOARD_USER_FONT_SIZE: 28,
  LEADERBOARD_RESULT_FONT_SIZE: 40,

  PADDING: 48,
  ROW_HEIGHT: 100,
  RANKING_CONTENT_INSET: 150,
  ROW_GAP: 8,
  LEAGUE_GAP: 20,
  LOGO_SIZE: 72,
  LEADERBOARD_LOGO_SIZE: 70,
  STRIP_WIDTH: 90,
  LEAGUE_LABEL_WIDTH: 80,
  LEAGUE_OFFSET: 200,
  LEAGUE_TO_MATCH_GAP: 1,
  MATCH_CONTENT_INSET: 200,
  MATCH_ROW_INSET: 5,
  SCORE_BLOCK_GAP: 20,

  WATERMARK_OPACITY: 0.3,
  WATERMARK_SIZE: 800,
};
